apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: vinhlee95/fibo-server
          ports:
            - containerPort: 3003
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service # name of the redis clusterIP service
            - name: REDIS_PORT
              value: "6379"
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service # name of the postgres clusterIP service
            - name: PGDATABASE
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGPASSWORD
              valueFrom: # https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
